type=page
status=published
title=Eclipse Open Message Queue Release Notes, Release 6.3.0
next=preface.html
prev=toc.html
~~~~~~
Eclipse Open Message Queue Release Notes, Release 6.3.0
=======================================================

[[open-message-queue]]
Eclipse Open Message Queue
--------------------------

Release Notes

Release 6.3.0

Contributed 2018, 2022

This book describes new features, compatibility issues, and existing
bugs for the Message Queue 6.3.0, 6.1.0, 6.0.0 and earlier releases.

[[sthref1]]

'''''

Eclipse Open Message Queue Release Notes, Release 6.3.0

Copyright © 2013, 2020 Oracle and/or its affiliates. All rights reserved. +
Copyright © 2021, 2022 Contributors to the Eclipse Foundation

This program and the accompanying materials are made available under the 
terms of the Eclipse Public License v. 2.0, which is available at 
http://www.eclipse.org/legal/epl-2.0. 

SPDX-License-Identifier: EPL-2.0

Oracle and Java are registered trademarks of Oracle and/or its 
affiliates. Other names may be trademarks of their respective owners. 

Intel and Intel Xeon are trademarks or registered trademarks of Intel 
Corporation. All SPARC trademarks are used under license and are 
trademarks or registered trademarks of SPARC International, Inc. AMD, 
Opteron, the AMD logo, and the AMD Opteron logo are trademarks or 
registered trademarks of Advanced Micro Devices. UNIX is a registered 
trademark of The Open Group. 

