theme: jekyll-theme-architect

title: [mq-release-notes]
description: [Eclipse Open Message Queue Release Notes, Release 6.1.0]

# sidebar links url
links:
  source: https://github.com/eclipse-ee4j/openmq/tree/master/docs/mq/mq-release-notes
  download: https://github.com/eclipse-ee4j/openmq/releases
  #mailinglist: https://javaee.groups.io/g/mq-release-notes
  #javadocs:
  docs: https://eclipse-ee4j.github.io/openmq/guides/mq-release-notes/toc.html
  #faq:

