type=page
status=published
<<<<<<< HEAD
title=Eclipse Open Message Queue Developer's Guide for C Clients, Release 5.1.3
next=preface.html
prev=lot.html
~~~~~~
Eclipse Open Message Queue Developer's Guide for C Clients, Release 5.1.3
=======
title=Eclipse Open Message Queue Developer's Guide for C Clients, Release 5.1.4
next=preface.html
prev=lot.html
~~~~~~
Eclipse Open Message Queue Developer's Guide for C Clients, Release 5.1.4
>>>>>>> 2f2a2fb8c08af74869f6549c182b3f7058278df8
=========================================================================

[[open-message-queue]]
Eclipse Open Message Queue
--------------------------

Developer's Guide for C Clients

<<<<<<< HEAD
Release 5.1.3
=======
Release 5.1.4
>>>>>>> 2f2a2fb8c08af74869f6549c182b3f7058278df8

Contributed 2018, 2019

This guide provides programming and reference information for developers
working with Message Queue who want to use the C language binding to the
Message Queue Service to send, receive, and process Message Queue
messages.

[[sthref1]]

'''''

<<<<<<< HEAD
Eclipse Open Message Queue Developer's Guide for C Clients, Release 5.1.3
=======
Eclipse Open Message Queue Developer's Guide for C Clients, Release 5.1.4
>>>>>>> 2f2a2fb8c08af74869f6549c182b3f7058278df8

Copyright © 2013, 2019 Oracle and/or its affiliates. All rights reserved.

This program and the accompanying materials are made available under the 
terms of the Eclipse Public License v. 2.0, which is available at 
http://www.eclipse.org/legal/epl-2.0. 

SPDX-License-Identifier: EPL-2.0

Oracle and Java are registered trademarks of Oracle and/or its 
affiliates. Other names may be trademarks of their respective owners. 

Intel and Intel Xeon are trademarks or registered trademarks of Intel 
Corporation. All SPARC trademarks are used under license and are 
trademarks or registered trademarks of SPARC International, Inc. AMD, 
Opteron, the AMD logo, and the AMD Opteron logo are trademarks or 
registered trademarks of Advanced Micro Devices. UNIX is a registered 
trademark of The Open Group. 

