name: Test Broker backed by JDBC (Oracle)
on:
  workflow_call:
    inputs:
      java_version:
        type: string
        default: 21
      java_distribution:
        type: string
        default: temurin
      java_package:
        type: string
        default: jre

jobs:
  broker-jdbc-backed:
    name: Test Broker backed by JDBC (Oracle, ${{ inputs.java_version }}-${{ inputs.java_package }})
    runs-on: ubuntu-latest
    services:
      oracle:
        image: container-registry.oracle.com/database/free:latest-lite
        ports:
          - 1521

    env:
      ORACLE_DATABASE: FREEPDB1
      ORACLE_ADMIN_PASS: oradmin
      ORACLE_USER: openmq
      ORACLE_PASS: openmq
      MQ_DISTRIBUTION_ROOT: mq-distribution
      MQ_DISTRIBUTION_HOME: mq-distribution/mq
      MQ_VAR_HOME: mq-var-home
      MQ_ZIP: mq.zip

    steps:
    - name: Change the Default Password for SYS User
      run: docker exec ${{ job.services.oracle.id }} ./setPassword.sh ${ORACLE_ADMIN_PASS}
    - name: Check Oracle status
      run: docker logs ${{ job.services.oracle.id }}
    - name: Create user files
      run: |
        echo "create user ${ORACLE_USER} identified by ${ORACLE_PASS} quota unlimited on system;" > user.sql
        echo "grant create session to ${ORACLE_USER};" > permissions.sql
        echo "grant create table to ${ORACLE_USER};" >> permissions.sql
        echo "grant create sequence to ${ORACLE_USER};" >> permissions.sql
        cat user.sql permissions.sql
        docker cp user.sql ${{ job.services.oracle.id }}:/tmp
        docker cp permissions.sql ${{ job.services.oracle.id }}:/tmp
    - name: Create DB user
      run: |
        for sqlScript in user.sql \
                         permissions.sql
        do
          docker exec -t ${{ job.services.oracle.id }} \
            bash -c "sqlplus -S sys/${ORACLE_ADMIN_PASS}@${ORACLE_DATABASE} as sysdba < /tmp/${sqlScript}"
        done
    - name: Download MQ Distribution
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: mq.zip
        skip-decompress: true
    - name: Unzip MQ Distribution
      run: unzip -q -d ${MQ_DISTRIBUTION_ROOT} ${MQ_ZIP}
    - name: Set up Java
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}
        java-package: ${{ inputs.java_package }}
    - name: Prepare admin passfile
      run: echo imq.imqcmd.password=admin > admin.pass
    - name: Download Oracle driver
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: broker-jdbc-drivers-oracle
        path: jdbc-drivers
    - name: Extend OpenMQ with JDBC driver
      run: |
        mv -v \
          jdbc-drivers/*.jar \
          $(find ${MQ_DISTRIBUTION_ROOT} -name ext -type d)
    - name: Update passfile for database
      run: echo imq.persist.jdbc.password=${ORACLE_PASS} >> admin.pass
    - name: Start broker backed by Oracle
      env:
        JAVA_TOOL_OPTIONS: "-enableassertions"
      run: |
        nohup ${MQ_DISTRIBUTION_HOME}/bin/imqbrokerd \
          -Dimq.persist.store=jdbc \
          -Dimq.persist.jdbc.dbVendor=oracle \
          -Dimq.persist.jdbc.oracle.property.url=jdbc:oracle:thin:@localhost:${{ job.services.oracle.ports[1521] }}/${ORACLE_DATABASE} \
          -Dimq.persist.jdbc.oracle.opendburl=jdbc:oracle:thin:@localhost:${{ job.services.oracle.ports[1521] }}/${ORACLE_DATABASE} \
          -Dimq.persist.jdbc.oracle.needpassword=true \
          -Dimq.brokerid=Lambda \
          -name Lambda \
          -dbuser ${ORACLE_USER} \
          -passfile admin.pass \
          -varhome ${MQ_VAR_HOME} >brokerd.log 2>&1 &
    - name: Wait for broker to start
      timeout-minutes: 1
      run: |
         while [ true ]
         do
           grep \
             --with-filename \
             --extended-regexp \
             "Broker .*@.*:7676. ready." \
             ${MQ_VAR_HOME}/instances/*/log/log.txt && break
           sleep 10s
         done
    - name: List broker
      env:
        JAVA_TOOL_OPTIONS: "-enableassertions"
      run: |
        ${MQ_DISTRIBUTION_HOME}/bin/imqcmd \
          -u admin \
          -passfile admin.pass \
          list bkr | tee list-bkr.log
    - name: Send several messages
      run: |
        for id in Oscar Papa Echo November Mike Quebec
        do
          java \
            -cp ${MQ_DISTRIBUTION_HOME}/lib/jms.jar:${MQ_DISTRIBUTION_HOME}/lib/imq.jar:${MQ_DISTRIBUTION_HOME}/examples/helloworld/helloworldmessage \
            -DHelloWorldMessage.receive=false \
            HelloWorldMessage ${id}
        done | tee send.log
    - name: Receive messages with timeout
      run: |
        for message in O P E N M Q
        do
          java \
            -cp ${MQ_DISTRIBUTION_HOME}/lib/jms.jar:${MQ_DISTRIBUTION_HOME}/lib/imq.jar:${MQ_DISTRIBUTION_HOME}/examples/helloworld/helloworldmessage \
            -DHelloWorldMessage.send=false \
            -DHelloWorldMessage.receiveTimeoutMillis=10000 \
            HelloWorldMessage $@
        done | tee receive.log
    - name: Verify expected messages
      run: |
        for id in Oscar Papa Echo November Mike Quebec
        do
          grep --silent "Read Message: Hello World: ${id}" receive.log || echo "Missing: ${id}" | tee -a missing.log
        done
        test ! -s missing.log
    - name: Stop broker
      timeout-minutes: 1
      if: always()
      env:
        JAVA_TOOL_OPTIONS: "-enableassertions"
      run: |
        ${MQ_DISTRIBUTION_HOME}/bin/imqcmd \
          -f \
          -u admin \
          -passfile admin.pass \
          shutdown bkr 2>/dev/null
    - name: Upload logs
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: always()
      with:
        name: broker-jdbc-backed-logs-oracle-${{ inputs.java_version }}-${{ inputs.java_package }}
        retention-days: 1
        path: |
          brokerd.log
          list-bkr.log
          send.log
          receive.log
          missing.log
          ${{ env.MQ_VAR_HOME }}/instances/*/log/log.txt
