#
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

on:
  workflow_call:
    inputs:
      java_distribution:
        required: false
        type: string
        default: 'temurin'
      java_version:
        required: true
        type: string

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout for build
      uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}
    - name: Docs Maven Build
      run: ./mvnw --show-version --no-transfer-progress --file docs install --define skipSBOM
