#
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

on:
  workflow_call:
    inputs:
      java_distribution:
        required: false
        type: string
        default: 'temurin'
      java_version:
        required: true
        type: string

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout for build
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Set up JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}
    - name: Docs Maven Build
      run: ./mvnw --show-version --no-transfer-progress --file docs install --define skipSBOM
    - name: Upload mq-admin-guide
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: mq-admin-guide
        retention-days: 1
        path: docs/mq-admin-guide/target/staging
    - name: Upload mq-dev-guide-c
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: mq-dev-guide-c
        retention-days: 1
        path: docs/mq-dev-guide-c/target/staging
    - name: Upload mq-dev-guide-java
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: mq-dev-guide-java
        retention-days: 1
        path: docs/mq-dev-guide-java/target/staging
    - name: Upload mq-dev-guide-jmx
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: mq-dev-guide-jmx
        retention-days: 1
        path: docs/mq-dev-guide-jmx/target/staging
    - name: Upload mq-release-notes
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: mq-release-notes
        retention-days: 1
        path: docs/mq-release-notes/target/staging
    - name: Upload mq-tech-over
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: mq-tech-over
        retention-days: 1
        path: docs/mq-tech-over/target/staging
