#
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

name: Eclipse OpenMQ integrate with LDAP

on:
  workflow_call:
    inputs:
      java_version:
        type: string
        default: 21
      java_distribution:
        type: string
        default: temurin
      java_package:
        type: string
        default: jre
      mq_distribution_artifact:
        type: string
        default: 'mq-distribution'

jobs:
  prepare-files-for-ldap-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Upload config files
      uses: actions/upload-artifact@v4
      with:
        name: ldap-integration-config-files
        retention-days: 1
        path: |
          .github/workflows-etc/it-ldap/admin.pass
          .github/workflows-etc/it-ldap/admin-ldap.pass
          .github/workflows-etc/it-ldap/ldap-data.ldif

  integrate-with-ldap:
    name: Integrate with LDAP
    needs:
    - prepare-files-for-ldap-tests
    runs-on: ubuntu-latest
    env:
      LDAP4MQ_PORT: 21389

    steps:
    - name: Download MQ Distribution
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.mq_distribution_artifact }}
    - name: Download Config Files
      uses: actions/download-artifact@v4
      with:
        name: ldap-integration-config-files
    - name: Download OpenDJ distribution
      run: |
        wget --quiet \
             https://github.com/OpenIdentityPlatform/OpenDJ/releases/download/4.10.1/opendj-4.10.1.zip \
             --output-document=opendj.zip
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}
        java-package: ${{ inputs.java_package }}
    - name: Extract OpenDJ
      run: unzip -q opendj.zip
    - name: Setup OpenDJ
      run: |
        opendj/setup \
          --cli \
          --no-prompt \
          --rootUserPassword password \
          --baseDN dc=openmq,dc=eclipse,dc=org \
          --ldifFile $(realpath ldap-data.ldif) \
          --ldapPort ${LDAP4MQ_PORT}
    - name: Extract Current MQ Distribution
      run: unzip -d mq-current -q mq.zip
    - name: Start MQ Broker Daemon
      timeout-minutes: 2
      run: |
        nohup mq-current/mq/bin/imqbrokerd \
          -Dimq.service.activelist=admin \
          -verbose \
          -varhome mqvar > mq-current/brokerd-init.log 2>&1 &
        while [ true ]
        do
          grep "Broker .*:7676.*ready" mq-current/brokerd-init.log && break
          sleep 10s
        done
    - name: Shutdown MQ Broker Daemon
      run: mq-current/mq/bin/imqcmd -u admin -f -passfile admin.pass shutdown bkr
    - name: Update instance to work with LDAP
      run: |
        for acf in $(find mqvar -name accesscontrol.properties)
        do
          echo >> ${acf}
          echo '# allow mqadmin from LDAP' >> ${acf}
          echo 'connection.ADMIN.allow.user=mqadmin' >> ${acf}
        done
    - name: Start MQ Broker Daemon with LDAP
      timeout-minutes: 2
      run: |
        nohup mq-current/mq/bin/imqbrokerd \
          -Dimq.service.activelist=jms,admin \
          -verbose \
          -Dimq.authentication.basic.user_repository=ldap \
          -Dimq.authentication.type=basic \
          -Dimq.user_repository.ldap.server=localhost:${LDAP4MQ_PORT} \
          -Dimq.user_repository.ldap.base=ou=people,dc=openmq,dc=eclipse,dc=org \
          -Dimq.user_repository.ldap.uidattr=uid \
          -varhome mqvar > mq-current/brokerd.log 2>&1 &
        while [ true ]
        do
          grep "Broker .*:7676.*ready" mq-current/brokerd.log && break
          sleep 10s
        done
    - name: List services
      run: mq-current/mq/bin/imqcmd -u mqadmin -f -passfile admin-ldap.pass list svc
    - name: Shutdown MQ Broker Daemon
      run: mq-current/mq/bin/imqcmd -u mqadmin -f -passfile admin-ldap.pass shutdown bkr
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: broker-logs-ldap-integration
        retention-days: 1
        path: |
          mq-*/brokerd*.log
