#
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

name: Eclipse OpenMQ integrate with LDAP

on:
  workflow_dispatch:

jobs:
  integrate-with-ldap:
    name: Integrate with LDAP
    runs-on: ubuntu-latest

    services:
      ldap:
        image: openidentityplatform/opendj:4.9.3
        credentials:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
        env:
          PORT: 389
          BASE_DN: ou=people,dc=openmq,dc=eclipse,dc=org
        ports:
          - 389

    steps:
    - name: Check OpenDJ status
      run: docker exec ${{ job.services.ldap.id }} /opt/opendj/bin/status -n -w password
    - name: List configured LDAP backends
      run: docker exec ${{ job.services.ldap.id }} /opt/opendj/bin/list-backends
