#
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string
      java_distribution:
        required: false
        type: string
        default: 'zulu'
      java_package:
        required: false
        type: string
        default: 'jre'
      mq_distribution_artifact:
        required: false
        type: string
        default: 'mq-distribution'
      mq_command:
        required: true
        type: string

jobs:
  smoke:
    name: Smoke Tests ${{ inputs.mq_command }} @ Java ${{ inputs.java_version }}
    runs-on: ubuntu-latest

    steps:
    - name: Download MQ Distribution
      uses: actions/download-artifact@v5
      with:
        name: ${{ inputs.mq_distribution_artifact }}
    - name: Unzip MQ Distribution
      run: unzip -q mq.zip
    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}
        java-package: ${{ inputs.java_package }}
    - name: Execute MQ Command
      run: mq/bin/${{ inputs.mq_command}} -version
